[package]
name = "quaireaux"
version = "0.1.0"
description = "A set of opinionated Cairo 1.0 libraries and algorithms."
homepage = "https://github.com/keep-starknet-strange/quaireaux"

[dependencies]
quaireaux_data_structures = {version = "0.1.0", path = "quaireaux/data_structures"} 
quaireaux_math = {version = "0.1.0", path = "quaireaux/math"} 
quaireaux_sorting = {version = "0.1.0", path = "quaireaux/sorting"} 
quaireaux_utils = {version = "0.1.0", path = "quaireaux/utils"} 