[package]
name = "quaireaux"
version = "0.1.0"
description = "A set of opinionated Cairo 1.0 libraries and algorithms."
homepage = "https://github.com/keep-starknet-strange/quaireaux"

[dependencies]
quaireaux_data_structures = “0.1.0”
quaireaux_math = “0.1.0”
quaireaux_sorting = “0.1.0”
quaireaux_utils = “0.1.0”