[package]
name = "quaireaux_data_structures"
version = "0.1.0"
description = "A set of data structures Cairo 1.0 libraries and algorithms"
homepage = "https://github.com/keep-starknet-strange/quaireaux/tree/main/data_structures"

[dependencies]
quaireaux_utils = { path = "../utils/" }
