[package]
name = "alexandria_storage"
version = "0.2.0"
description = "Starknet storage utilities"
homepage = "https://github.com/keep-starknet-strange/alexandria/tree/main/storage"

[[target.starknet-contract]]

[dependencies]
starknet = ">=2.1.0"
